export const GET_STUDENTS = "GET_STUDENTS";
export const POST_STUDENT = "POST_STUDENT";
export const GET_DEPARTAMENTO = "GET_DEPARTAMENTO";
export const POST_DEPARTAMENTO = "POST_DEPARTAMENTO";
export const POST_PLAN = "POST_PLAN";
export const GET_PLAN = "GET_PLAN";
export const POST_PERIODO = "POST_PERIODO";

//Para los cursos
export const POST_CURSO = "POST_CURSO";
export const GET_CURSOS = "GET_CURSOS";
export const GET_CURSO_BY_PLAN = "GET_CURSO_BY_PLAN";
export const GET_CURSOS_Y_NOTAS_CERTIFICADO = "GET_CURSOS_Y_NOTAS_CERTIFICADO";
export const GET_CURSO_BY_ID = "GET_CURSO_BY_ID";
export const GET_CURSO_BY_NAME = "GET_CURSO_BY_NAME";
export const UPDATE_CURSO = "UPDATE_CURSO";
export const POST_CURSOS_MASIVAMENTE = "POST_CURSOS_MASIVAMENTE";

export const GET_STUDENT_BY_DNI = "GET_STUDENT_BY_DNI";
export const CLEAN_STUDENT_BY_DNI = "CLEAN_STUDENT_BY_DNI";
export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID";

export const GET_PERIODO = "GET_PERIODO";
export const POST_NOTA = "POST_NOTA"

export const GET_ESTUDIANTES_BY_APELLIDOS = "GET_ESTUDIANTES_BY_APELLIDOS";
export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const CLEAN_CURRENT_STUDENT = "CLEAN_CURRENT_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const LOGIN = "LOGIN";
export const SIGNOUT = "SIGNOUT";
export const GET_ESTUDIANTE_NOTAS = "GET_ESTUDIANTE_NOTAS";
export const GET_NOTA_BY_ID = "GET_NOTA_BY_ID";
export const UPDATE_NOTA_BY_ID = "UPDATE_NOTA_BY_ID";
export const DELETE_NOTA = "DELETE_NOTA";
export const CREATE_USER = "CREATE_USER";

//PARA CARGA MASIVA DE ESTUDIANTES, CURSOS Y NOTAS
export const CARGA_MASIVA = "CARGA_MASIVA" //Para estudiantes
export const CARGA_MASIVA_CURSOS = "CARGA_MASIVA_CURSOS";
export const CARGA_MASIVA_NOTAS = "CARGA_MASIVA_NOTAS";


export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

export const ERROR_MESSAGE = "Falló la Operación 🟥!!";
export const SUCCESS_MESSAGE = "Operación Exitosa 👌!!"

//PARA LIMPIEZA
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CLEAR_PLAN = "CLEAR_PLAN";
export const CLEAR_DEPARTAMENTOS = "CLEAR_DEPARTAMENTOS";
